name: PR Build Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Rust cache
        uses: actions/cache@v3
        id: rust-cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Setup Rust (MSVC)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rust-src
          cache: 'true'
          rustflags: '-Awarnings'
          cache-directories:
            ~/.cargo/registry
            ~/.cargo/git
            target


      - name: Test Rust
        run: cargo test --all